# Settings (H2 Database)
# Path: http://localhost:8080/h2-console
#server.port=9092
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
## Enable console
#spring.h2.console.enabled=true
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.show-sql=true

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/Kam
    username: postgres
    password: 112233qq
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    baseline-on-migrate: true